spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:database
jwt.secret=they-told-him-dont-you-ever-come-around-here-dont-wanna-see-your-face-you-better-dissappear
